BITS = 32

INT_FRAC_LEN = 15
INT_INT_LEN = 16  

FLOAT_EXP_LEN = 8
FLOAT_MANT_LEN = 23
FLOAT_EXP_BIAS = 127
FLOAT_MANT_IMPLICIT_LEN = 24 

BCD_MAX_DIGITS = 8
BCD_DIGIT_BITS = 4
BCD_CORRECTION_THRESHOLD = 9
BCD_CORRECTION_VALUE = 6
BCD_CARRY_THRESHOLD = 15
BCD_MODULO = 16
BCD_BASE = 10
